version: '3.3'
services:
  cur8:
    build:
      context: ./apps/cur8
      dockerfile: Dockerfile.dev
      args:
        uid: ${DOCKER_COMPOSE_UID:-1000}
    volumes:
      - ./apps/cur8:/srv:delegated
      - gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cur8
      DB_PASS: development

  ct-api:
    command: ["wait-then", "mix", "phx.server"]
    build:
      context: ./apps/ct-api
      dockerfile: Dockerfile.dev
      args:
        uid: ${DOCKER_COMPOSE_UID:-1000}
    volumes:
      - ./apps/ct-api:/srv:delegated
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cashtracker
      DB_PASS: development

  ct-web:
    command: ["yarn", "run", "start", "--port", "3000"]
    ports:
      - 4000:3000
    build:
      context: ./apps/ct-web
      dockerfile: Dockerfile.dev
      args:
        uid: ${DOCKER_COMPOSE_UID:-1000}
    volumes:
      - ./apps/ct-web:/srv:delegated
      - yarn:/home/cashtracker/.cache/yarn
      - yarn:/home/cashtracker2/.cache/yarn

  postgres:
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      CUR8_USER: cur8
      CUR8_PASS: development
      CT_USER: cashtracker
      CT_PASS: development

  redis:
    ports:
      - 63791:6379

volumes:
  gems:
  yarn:
