version: '3.3'
services:
  cur8:
    image: docker.pkg.github.com/jhollinger/cur8/cur8:0.1
    restart: always
    env_file:
      - ./env/cur8

  ct-api:
    command: ["foreground"]
    image: docker.pkg.github.com/jhollinger/cashtracker-api/ct-api:0.2
    restart: always
    env_file:
      - ./env/ct-api

  ct-web:
    ports:
      - 4000:80
    image: docker.pkg.github.com/jhollinger/cashtracker-web/ct-web:0.2
    restart: always

  music-camp:
    image: docker.pkg.github.com/jhollinger/music-camp/music-camp:0.1
    restart: always
    environment:
      RACK_ENV: production
    volumes:
      - ./mounts/music-camp/downloads:/srv/downloads
      - ./mounts/music-camp/media:/srv/public/media
      - ./mounts/music-camp/photos:/srv/public/photos
      - ./mounts/music-camp/db.sqlite3:/srv/db/db.sqlite3
      - ./env/music-camp.yml:/srv/config/music-camp.yml
      - ./env/music-camp.database.yml:/srv/config/database.yml

  postgres:
    restart: always
    env_file:
      - ./env/postgres
