FROM ruby:2.3-stretch
WORKDIR /srv
ARG uid=1000

ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_PATH="$GEM_HOME" \
  BUNDLE_SILENCE_ROOT_WARNING=1 \
  BUNDLE_APP_CONFIG="$GEM_HOME"
ENV PATH $GEM_HOME/bin:$BUNDLE_PATH/gems/bin:$PATH

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.6.0/wait /usr/local/bin/wait
RUN chmod +x /usr/local/bin/wait && \
  echo '#!/bin/bash\nwait; exec "$@"' > /usr/local/bin/wait-then && chmod 755 /usr/local/bin/wait-then

RUN apt-get update && \
  apt-get install -y \
    imagemagick \
    node.js \
    vim-tiny && \
  useradd -m app && \
  useradd -m app2 && \
  mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME" && \
  echo '#!/bin/bash\nbundle exec "$@"' > /usr/local/bin/b && chmod 755 /usr/local/bin/b

USER $uid
