version: '3.3'
services:
  ct-api:
    environment:
      WAIT_HOSTS: postgres:5432
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - main

  ct-web:
    networks:
      - main

  #cur8:
  #  command: ["wait-then", "bundle", "exec", "puma", "-p", "3000", "-b", "tcp://0.0.0.0", "--pidfile", "/tmp/puma.pid"]
  #  environment:
  #    WAIT_HOSTS: postgres:5432, redis:6379
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    - postgres
  #    - redis
  #  networks:
  #    - main

  #music-camp:
  #  command: ["wait-then", "bundle", "exec", "puma", "-p", "3000", "-b", "tcp://0.0.0.0", "--pidfile", "/tmp/puma.pid"]
  #  ports:
  #    - 5000:3000
  #  networks:
  #    - main

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./mounts/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - main

  redis:
    image: redis:5.0.7-alpine
    networks:
      - main

volumes:
  pg-data:

networks:
  main:
