version: '3.3'
services:
  cur8:
    image: docker.pkg.github.com/jhollinger/cur8/cur8:0.1
    restart: always
    env_file:
      - cur8.env

  ct-api:
    command: ["foreground"]
    image: docker.pkg.github.com/jhollinger/cashtracker-api/ct-api:0.2
    restart: always
    env_file:
      - ct-api.env

  ct-web:
    ports:
      - 4000:80
    image: docker.pkg.github.com/jhollinger/cashtracker-web/ct-web:0.2
    restart: always

  postgres:
    restart: always
    env_file:
      - postgres.env
