FROM ruby:2.3.8-alpine3.8
WORKDIR /srv

ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_PATH="$GEM_HOME" \
  BUNDLE_APP_CONFIG="$GEM_HOME"

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.6.0/wait /usr/local/bin/wait
RUN chmod +x /usr/local/bin/wait && \
  printf '#!/bin/bash\nwait; exec "$@"' > /usr/local/bin/wait-then && chmod 755 /usr/local/bin/wait-then

RUN mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME" && \
  printf '#!/bin/bash\nbundle exec "$@"' > /usr/local/bin/b && chmod 755 /usr/local/bin/b

RUN apk --no-cache add \
  bash \
  build-base \
  libxml2-dev \
  libxslt-dev \
  postgresql-dev \
  sqlite-dev \
  imagemagick \
  tzdata \
  nodejs \
  git \
  vim

RUN adduser --disabled-password app
USER app
